#!/usr/bin/env bash

source bam-sh-setup

case "$1" in
  -h|--help)
    exec man bam-gen
    shift
    ;;
esac

envlog="build-env.log"
jsonfile="build.json"
write_buildenv "$BAM_OUTPUT_PATH/.buildenv"

exec gn --root="$BAM_SOURCE_ROOT" --envlog="$envlog" --ide=json --json-file-name="$jsonfile" --export-compile-commands-per-toolchain gen "$BAM_OUTPUT_PATH" "$@"
